#ifndef __G3507_HW_CONFIG_H
#define __G3507_HW_CONFIG_H

#include "ti/driverlib/dl_gpio.h" /* GPIO_Pin_x + GPIOA/B 原语，其余枚举值在 Enroll.c 展开时由 Enroll_Internal.h 提供 */

/*
 * G3507_hw_config.h 板级硬件映射宏
 * 只维护实际用到的端口/引脚/IOMUX，注册和查找都在这里完成。
 */

/* LED 板级映射 */
#define HW_LED_MAP(X) \
    X(LED1, GPIOB, DL_GPIO_PIN_14)\
    X(LED2, GPIOA, DL_GPIO_PIN_29)\
    X(LED3, GPIOA, DL_GPIO_PIN_28)\
    X(Buzzer1, GPIOA, DL_GPIO_PIN_14)

/* USART0 板级映射 */
#define HW_USART0_TX_PORT GPIOA
#define HW_USART0_TX_PIN  DL_GPIO_PIN_10
#define HW_USART0_RX_PORT GPIOA
#define HW_USART0_RX_PIN  DL_GPIO_PIN_11

#define G3507_USART0_TX_IOMUX IOMUX_PINCM21
#define G3507_USART0_TX_FUNC  IOMUX_PINCM21_PF_UART0_TX
#define G3507_USART0_RX_IOMUX IOMUX_PINCM22
#define G3507_USART0_RX_FUNC  IOMUX_PINCM22_PF_UART0_RX

/* USART1 板级映射 */
#define HW_USART1_TX_PORT GPIOA
#define HW_USART1_TX_PIN  DL_GPIO_PIN_8
#define HW_USART1_RX_PORT GPIOA
#define HW_USART1_RX_PIN  DL_GPIO_PIN_9

#define G3507_USART1_TX_IOMUX IOMUX_PINCM19
#define G3507_USART1_TX_FUNC  IOMUX_PINCM19_PF_UART1_TX
#define G3507_USART1_RX_IOMUX IOMUX_PINCM20
#define G3507_USART1_RX_FUNC  IOMUX_PINCM20_PF_UART1_RX

/* USART2 板级映射 */
#define HW_USART2_TX_PORT GPIOB
#define HW_USART2_TX_PIN  DL_GPIO_PIN_15
#define HW_USART2_RX_PORT GPIOB
#define HW_USART2_RX_PIN  DL_GPIO_PIN_16

#define G3507_USART2_TX_IOMUX IOMUX_PINCM32
#define G3507_USART2_TX_FUNC  IOMUX_PINCM32_PF_UART2_TX
#define G3507_USART2_RX_IOMUX IOMUX_PINCM33
#define G3507_USART2_RX_FUNC  IOMUX_PINCM33_PF_UART2_RX

#define HW_USART_MAP(X) \
    X(API_USART1, API_USART_CORE_UART0, HW_USART0_TX_PORT, HW_USART0_TX_PIN, HW_USART0_RX_PORT, HW_USART0_RX_PIN)\
    X(API_USART2, API_USART_CORE_UART1, HW_USART1_TX_PORT, HW_USART1_TX_PIN, HW_USART1_RX_PORT, HW_USART1_RX_PIN)\
    X(API_USART3, API_USART_CORE_UART2, HW_USART2_TX_PORT, HW_USART2_TX_PIN, HW_USART2_RX_PORT, HW_USART2_RX_PIN)

/* TIM 板级映射 */
#define HW_TIM_MAP(X) \
    X(API_TIM1, API_TIM_CORE_TIMG0) \
    X(API_TIM2, API_TIM_CORE_TIMG6)

/* PWM 板级映射：PA16 -> TIMA1 CCP1，PA17 -> TIMA1 CCP0。 */
#define G3507_PWM_TIMA1_CH1_PORT  GPIOA
#define G3507_PWM_TIMA1_CH1_PIN   DL_GPIO_PIN_16
#define G3507_PWM_TIMA1_CH1_IOMUX IOMUX_PINCM38
#define G3507_PWM_TIMA1_CH1_FUNC  IOMUX_PINCM38_PF_TIMA1_CCP1

#define G3507_PWM_TIMA1_CH0_PORT  GPIOA
#define G3507_PWM_TIMA1_CH0_PIN   DL_GPIO_PIN_17
#define G3507_PWM_TIMA1_CH0_IOMUX IOMUX_PINCM39
#define G3507_PWM_TIMA1_CH0_FUNC  IOMUX_PINCM39_PF_TIMA1_CCP0

#define HW_PWM_MAP(X) \
    X(API_PWM_TIM1, API_PWM_CH1, API_PWM_CORE_TIMA1, API_PWM_CORE_CCP0, G3507_PWM_TIMA1_CH0_PORT, G3507_PWM_TIMA1_CH0_PIN) \
    X(API_PWM_TIM1, API_PWM_CH2, API_PWM_CORE_TIMA1, API_PWM_CORE_CCP1, G3507_PWM_TIMA1_CH1_PORT, G3507_PWM_TIMA1_CH1_PIN)

/* 软件 I2C1： GPIOB PB2(SCL)/PB3(SDA) */
#define HW_I2C1_SCL_PORT GPIOB
#define HW_I2C1_SCL_PIN  DL_GPIO_PIN_2
#define HW_I2C1_SCL_IOMUX IOMUX_PINCM15 /* PB2 */
#define HW_I2C1_SDA_PORT GPIOB
#define HW_I2C1_SDA_PIN  DL_GPIO_PIN_3
#define HW_I2C1_SDA_IOMUX IOMUX_PINCM16 /* PB3 */

/* I2C 板级映射：注册 2 路软件 I2C。 */
#define HW_I2C_MAP(X) \
    X(API_I2C1, HW_I2C1_SCL_PORT, HW_I2C1_SCL_PIN, HW_I2C1_SDA_PORT, HW_I2C1_SDA_PIN, HW_I2C1_SCL_IOMUX, HW_I2C1_SDA_IOMUX)

/* 软件 SPI1：SCK=PB9，MOSI=PB8，MISO=PB7，CS=PB14 */
#define HW_SPI1_SCK_PORT  GPIOB
#define HW_SPI1_SCK_PIN   DL_GPIO_PIN_9
#define HW_SPI1_SCK_IOMUX IOMUX_PINCM26

#define HW_SPI1_MOSI_PORT GPIOB
#define HW_SPI1_MOSI_PIN  DL_GPIO_PIN_8
#define HW_SPI1_MOSI_IOMUX IOMUX_PINCM25

#define HW_SPI1_MISO_PORT GPIOB
#define HW_SPI1_MISO_PIN  DL_GPIO_PIN_6
#define HW_SPI1_MISO_IOMUX IOMUX_PINCM23

#define HW_SPI1_CS_PORT   GPIOA
#define HW_SPI1_CS_PIN    DL_GPIO_PIN_13
#define HW_SPI1_CS_IOMUX  IOMUX_PINCM35

/* SPI 板级映射：注册 1 路软件 SPI。 */
#define HW_SPI_MAP(X) \
        X(API_SPI1, HW_SPI1_CS_PORT, HW_SPI1_CS_PIN, \
            HW_SPI1_SCK_PORT, HW_SPI1_SCK_PIN, \
            HW_SPI1_MOSI_PORT, HW_SPI1_MOSI_PIN, \
            HW_SPI1_MISO_PORT, HW_SPI1_MISO_PIN, HW_SPI1_CS_IOMUX, HW_SPI1_SCK_IOMUX, HW_SPI1_MOSI_IOMUX, HW_SPI1_MISO_IOMUX)

/* MPU6050 INT 板级映射：PB4，对应 IOMUX_PINCM17。 */
#define HW_MPU6050_INT_PORT  GPIOB
#define HW_MPU6050_INT_PIN   DL_GPIO_PIN_25
#define HW_MPU6050_INT_IOMUX IOMUX_PINCM56

/* 当前板子上注册了 4 个LED */
#define HW_LED_COUNT    4U
/* 当前板子上注册了 3 路 USART */
#define HW_USART_COUNT  3U
/* 当前板子上注册了 2 路 PWM*/
#define HW_PWM_COUNT    2U
/* 当前板子上注册了 2 路 TIM */
#define HW_TIM_COUNT    2U
/* 当前板子上注册了 1 路软件 I2C */
#define HW_I2C_COUNT  1U
/* 当前板子上注册了 1 路软件 SPI */
#define HW_SPI_COUNT  1U
/* 当前板子上注册了 1 路 MPU6050 INT 引脚 */
#define HW_MPU6050_COUNT 1U

#endif /* __G3507_HW_CONFIG_H */
